# Wokwi for VS Code: simulate one of the examples.
# 1. cargo build --release
# 2. set the example in the two paths below
# 3. F1 -> "Wokwi: Start Simulator"
[wokwi]
version = 1
firmware = "target/riscv32imc-unknown-none-elf/release/wifi_dhcp"
elf = "target/riscv32imc-unknown-none-elf/release/wifi_dhcp"
gdbServerPort = 3333
